In [2]:
# 정규화
# - 개별 데잍의 크기를 모두 같게 만들기 위한 변환
# - 다차원 독립변수 벡터가 있을 때, 각 벡터 원소들의 상대적인 크기만 중요한 경웨 사용
# - normalize(X)

from sklearn.preprocessing import scale, normalize
import numpy as np
x = (np.arange(5, dtype=np.float64) - 20).reshape(-1, 1)
print(x)
y1 = scale(x)
y2 = normalize(x)

print(y1)
print(y2)

[[-20.]
 [-19.]
 [-18.]
 [-17.]
 [-16.]]
[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]
[[-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]]
