In [4]:
# 리스트 슬라이싱
import numpy as np

array = np.arange(0, 15).reshape(3, 5)
print(array)
print()
print(array[1:, 1:])
print()
print(array[:2, :1])
print()
print(array[1:2, 3:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 6  7  8  9]
 [11 12 13 14]]

[[0]
 [5]]

[[8 9]]


In [6]:
array = np.arange(0, 24).reshape(3, 2, 4)
print(array)
print()
print(array[1:, 1:, :1])
print()
print(array[1:, 0:, :3])
print()
print(array[1:3, 1:4, 1:5])

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

[[[12]]

 [[20]]]

[[[ 8  9 10]
  [12 13 14]]

 [[16 17 18]
  [20 21 22]]]

[[[13 14 15]]

 [[21 22 23]]]


In [8]:
# 벡터 계산 1
ar = np.array([1, 2, 3, 4, 5])
print(ar * 2)

[ 2  4  6  8 10]


In [11]:
# 벡터 계산 2
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b * 2
print(c)
print(c > 10)

[ 9 12 15]
[False  True  True]


In [13]:
# 벡터 계산 실습 1
# [7, 5, 9, 10]과 [4, 10, 6, 2] 인 2개의 배열을 생성
# 각 배열의 값을 3배로 만든 다음 더한 결과를 출력하시오

a = np.array([7, 5, 9, 10])
b = np.array([4, 10, 6, 2])

a = a * 3
b = b * 3
c = a + b
print(c)

[33 45 45 36]


In [16]:
# 벡터 계산 실습 2
# [[7, 5, 9, 10], [4, 10, 6, 2]] 과 [[1, 3, 4, 9], [14, 7, 6, 4]]인 2개의 배열을 생성
# 앞의 배열에서 뒤의 배열을 뺀 뒤 각 값이 양수인지 아닌지를 True, False로 출력하시오

a = np.array([[7, 5, 9, 10], [4, 10, 6, 2]])
b = np.array([[1, 3, 4, 9], [14, 7, 6, 4]])

c = a - b
print(c > 0)

[[ True  True  True  True]
 [False  True False False]]
