In [2]:
# 행렬곱 
# 행렬 A, B, C 가 주어졌을 때 이 규칙이 올바르게 적용되는지 확인해보자

import numpy as np

A = np.arange(0, 31, 2).reshape(4, 4)
B = np.arange(1, 32, 2).reshape(4, 4)
C = np.arange(2, 33, 2).reshape(4, 4)

print(A)
print()
print(B)
print()
print(C)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [7]:
# AB != BA
print(A @ B)
print()
print(B @ A)

AB != BA ? 
[[ 236  260  284  308]
 [ 652  740  828  916]
 [1068 1220 1372 1524]
 [1484 1700 1916 2132]]

[[ 272  304  336  368]
 [ 656  752  848  944]
 [1040 1200 1360 1520]
 [1424 1648 1872 2096]]


In [9]:
# A(B + C) == AB + AC
print(A @ (B + C))
print()
print((A @ B) + (A @ C))

[[ 484  532  580  628]
 [1348 1524 1700 1876]
 [2212 2516 2820 3124]
 [3076 3508 3940 4372]]

[[ 484  532  580  628]
 [1348 1524 1700 1876]
 [2212 2516 2820 3124]
 [3076 3508 3940 4372]]


In [10]:
# (A + B)C = AC + BC
print((A + B) @ C)
print()
print((A @ C) + (B @ C))

[[ 552  608  664  720]
 [1448 1632 1816 2000]
 [2344 2656 2968 3280]
 [3240 3680 4120 4560]]

[[ 552  608  664  720]
 [1448 1632 1816 2000]
 [2344 2656 2968 3280]
 [3240 3680 4120 4560]]


In [16]:
# (AB)T = BT AT
print((A @ B).T)
print()
print(B.T @ A.T)

[[ 236  652 1068 1484]
 [ 260  740 1220 1700]
 [ 284  828 1372 1916]
 [ 308  916 1524 2132]]

[[ 236  652 1068 1484]
 [ 260  740 1220 1700]
 [ 284  828 1372 1916]
 [ 308  916 1524 2132]]


In [25]:
# 실습 1
# 1 - 100의 정수로 (10, 10) 행렬을 생성한 후,
# np.random.shuffle() 을 이용하여 행렬을 뒤섞은 다음, 행렬을 정렬하시오

a = np.arange(1, 101).reshape(10, 10)
print(a)
print()
np.random.shuffle(a)
print('shuffle')
print(a)
print()

print('sort')
print(np.sort(a))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

shuffle
[[ 41  42  43  44  45  46  47  48  49  50]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 91  92  93  94  95  96  97  98  99 100]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 61  62  63  64  65  66  67  68  69  70]
 [  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 21  22  23  24  25  26  27  28  29  30]]

sort
[[ 41  42  43  44  45  46  47  48  49  50]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 91  92  93  94  95  96  97  98  99

In [26]:
# 실습 2
# 1 - 30 의 정수로 (3, 10) 행렬을 생성한 후,
# np.random.shuffle() 을 이용하여 행렬을 섞은 다음 axis 값을 바꾸어 정렬하시오

b = np.arange(1, 31).reshape(3, 10)
print(b)
print()

np.random.shuffle(b)
print('shuffle')
print(b)
print()

print('axis = 1')
print(np.sort(b, axis = 1))
print()
print('axis = 0')
print(np.sort(b, axis = 0))

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

shuffle
[[ 1  2  3  4  5  6  7  8  9 10]
 [21 22 23 24 25 26 27 28 29 30]
 [11 12 13 14 15 16 17 18 19 20]]

axis = 1
[[ 1  2  3  4  5  6  7  8  9 10]
 [21 22 23 24 25 26 27 28 29 30]
 [11 12 13 14 15 16 17 18 19 20]]

axis = 0
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
