In [3]:
import numpy as np

# array 생성하기 1
ar1 = np.array([1, 2, 3, 4, 5])

print(ar1)
print(type(ar1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# array 생성하기 2
ar2 = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
print(ar2)
print(len(ar2))
print(len(ar2[0]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3


In [9]:
# array 생성하기 3
ar3 = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])

print(ar3)
print('shape: ', ar3.shape)
print('ndim: ', ar3.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
shape:  (2, 2, 3)
ndim:  3


In [11]:
# 실습 
ar4 = np.array([10, 8, 15, 7, 19])

ar5 = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

ar6 = np.array([[[100, 90, 80],
                 [70, 60, 50]],
                [[15, 25, 35],
                 [45, 55, 65]],
                [[11, 22, 33],
                 [44, 55, 66]]])

print(ar4)
print(len(ar4))
print(ar4.ndim)
print(ar4.shape)
print()
print(ar5)
print(len(ar5))
print(ar5.ndim)
print(ar5.shape)
print()
print(ar6)
print(len(ar6))
print(ar6.ndim)
print(ar6.shape)
print()

[10  8 15  7 19]
5
1
(5,)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
3
2
(3, 3)

[[[100  90  80]
  [ 70  60  50]]

 [[ 15  25  35]
  [ 45  55  65]]

 [[ 11  22  33]
  [ 44  55  66]]]
3
3
(3, 2, 3)



In [14]:
# 배열 생성하기
a = np.zeros((3, 6)) # 0으로 된 3열 6행을 만든다
print(a)

b = np.ones((3, 6))
print(b)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [16]:
c = np.arange(100,110)  # 100 - 109으로 된 배열 만든다
print(c)

[100 101 102 103 104 105 106 107 108 109]


In [19]:
d = np.arange(100, 110).reshape(2, 5) # 100 - 109으로 된 2열 5행을 만든다
print(d)

[[100 101 102 103 104]
 [105 106 107 108 109]]


In [21]:
e = np.random.random((2, 5, 3))
print(e)

[[[0.15449392 0.68913695 0.92965487]
  [0.03689022 0.73520995 0.80597254]
  [0.54232462 0.71579628 0.24620868]
  [0.11707613 0.48719538 0.41694755]
  [0.69266356 0.38933691 0.21974007]]

 [[0.16583494 0.97284489 0.92203329]
  [0.75150954 0.68167143 0.83441021]
  [0.80029093 0.90497021 0.97759682]
  [0.77321976 0.44067679 0.97997096]
  [0.74167407 0.0052615  0.9994981 ]]]


In [24]:
# 실습
f = np.arange(10, 25).reshape(3, 5)
print(f)
print()

g = np.arange(11, 61).reshape(2, 5, 5)
print(g)
print()

h = np.arange(74, 250, step=5).reshape(3, 3, 4)
print(h)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[[11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]]

 [[36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

[[[ 74  79  84  89]
  [ 94  99 104 109]
  [114 119 124 129]]

 [[134 139 144 149]
  [154 159 164 169]
  [174 179 184 189]]

 [[194 199 204 209]
  [214 219 224 229]
  [234 239 244 249]]]
