In [2]:
# min, max
import numpy as np

ar = np.random.random((2, 2, 4))
print(ar)
print()
print(np.min(ar[:1, ]))
print()
print(np.max(ar))

[[[0.37318169 0.80487394 0.1053878  0.35966666]
  [0.74776913 0.28203912 0.90728222 0.48706516]]

 [[0.37399728 0.55384844 0.4224323  0.50959242]
  [0.59193698 0.68704535 0.76797349 0.93542606]]]

0.10538780469993736

0.9354260604986435


In [4]:
# argmin, argmax => 최대와 최소의 위치를 반환
print(np.argmin(ar))
print()

print(np.argmax(ar))

2

15


In [5]:
# sum, mean, median => 행렬 전체 합, 평균, 중간값을 계산
ar = np.arange(1, 31, 2).reshape(3, 5)
print(ar)
print()
print(np.sum(ar))
print()
print(np.mean(ar))
print()
print(np.median(ar))

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]]

225

15.0

15.0


In [8]:
# aixs: 0 은 행, 1은 열을 기준으로 계산
print(ar)
print()
print(np.sum(ar, axis = 0))
print()
print(np.sum(ar, axis = 1))
print()
print(np.sum(ar[1:], axis = 1))

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]]

[33 39 45 51 57]

[ 25  75 125]

[ 75 125]


In [10]:
# 실습 

a = np.array([[[0.5, 2. , 4. , -5.],
               [0.7, 9. , 3. , 0.7],
               [8. , 1. , -2. , 0.3]],
              
              [[1.2, 4. , 2. , -9. ],
               [8. , 3. , 2. , 1. ],
               [2. , 8. , 5. , -1. ]],
              [[3. , 9. , 6. , 0.8],
               [0.9, -1. , 3. , 4. ],
               [2. , 5. , 7. , 9. ]]])

print(a)
print()

[[[ 0.5  2.   4.  -5. ]
  [ 0.7  9.   3.   0.7]
  [ 8.   1.  -2.   0.3]]

 [[ 1.2  4.   2.  -9. ]
  [ 8.   3.   2.   1. ]
  [ 2.   8.   5.  -1. ]]

 [[ 3.   9.   6.   0.8]
  [ 0.9 -1.   3.   4. ]
  [ 2.   5.   7.   9. ]]]



In [12]:
# 실습 1
# 전체 행렬의 합, 평균과 중간값
print('전체 행렬의 합', np.sum(a))
print('전체 행렬의 평균', np.mean(a))
print('전체 행렬의 중간값', np.median(a))

전체 행렬의 합 97.1
전체 행렬의 평균 2.697222222222222
전체 행렬의 중간값 2.0


In [16]:
# 실습 2
# 2번째 행렬의 합, 최소값, 최대값
print('2번째 행렬의 합', np.sum(a[1:2]))
print('2번째 행렬의 최소값', np.min(a[1:2]))
print('2번째 행렬의 최대값', np.max(a[1:2]))

2번째 행렬의 합 26.2
2번째 행렬의 최소값 -9.0
2번째 행렬의 최대값 8.0


In [22]:
# 실습 3
# 1, 4번째 열을 제외한 부분 행렬의 최대, 최소, 평균, 중간값
print(a[:,:,1:3])
print(np.max(a[:,:,1:3]))
print(np.min(a[:,:,1:3]))
print(np.mean(a[:,:,1:3]))
print(np.median(a[:,:,1:3]))

[[[ 2.  4.]
  [ 9.  3.]
  [ 1. -2.]]

 [[ 4.  2.]
  [ 3.  2.]
  [ 8.  5.]]

 [[ 9.  6.]
  [-1.  3.]
  [ 5.  7.]]]
9.0
-2.0
3.888888888888889
3.5
